#!/usr/bin/env python
import sys

f = open(sys.argv[1])
num_accusers = int(f.readline())

grpA, grpB = set(), set()

for accuser in xrange(num_accusers):
    name, num = f.readline().split()
    liars = set()
    for i in xrange(int(num)):
        liars.add(f.readline().strip())
    if not(name in grpA or name in grpB):
        if liars <= grpA:
            grpB.add(name)
            grpA |= liars
        else:
            grpA.add(name)
            grpB |= liars        
    elif name in grpA:
        grpB |= liars
    else: #name in grpB
        grpA |= liars

a, b = len(grpA), len(grpB)
print max(a,b), min(a,b)
